# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Javier Martínez"
description: > # this means to ignore newlines until "email:"
   Welcome to my blog

email: javimartd@gmail.com
#blog logo
logo: "/assets/images/me3.png"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/bridge.jpg"

name: 'Javier Martínez'
author: 'Javier Martínez'
author_image: "/assets/images/m2.png"

paginate:	5

url: "" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
#twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	linkedin
    url:	https://www.linkedin.com/in/javier-mart%C3%ADnez-d%C3%ADaz/?locale=en_US
    desc: Find me on LinkedIn
    share_url:
    share_title:
    share_link:
